# 公開するページのURL
baseURL = "https://murphyfox.github.io"

languageCode = "ja"
DefaultContentLanguage = "ja"
HasCJKLanguage = true
enableRobotsTXT = true

# ブログのタイトル
title = "hiroki iida's notes"

theme = "mainroad"
paginate = 20

# 自己紹介
[Author]
    name = "Hiroki Iida"
    bio = "Salesforce界隈のひとです。"
    avatar = "img/avatar.png"

[Params]
    customCSS = ["css/custom.css"]
    copyright = "Author"
    readmore = true
    authorbox = true
    post_meta = ["date", "categories"]
    twitter_cards = true

# ページのテーマカラー
[Params.style.vars]
  highlightColor = "#1798c1"

# SNS等のユーザー名
[Params.widgets.social]
  twitter = "hiroki_iida_"

[[Params.widgets.social.custom]]
  title = "Trailblazer.me"
  url = "https://trailblazer.me/id/hiida"

[Params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    widgets = ["search", "recent", "categories", "taglist", "social"]

